- url: "https://github.com/i3/i3"
  depth: 0
  build: |-
    autoreconf -fi
    mkdir build && cd build
    ../configure --disable-sanitizers --disable-docs --disable-mans --enable-debug=no
    make
  requirements:
    build-dep:
      - i3-wm
    packages:
      - libxcb-shape0-dev
- url: "https://github.com/git/git"
  build: |-
    [[ -z $CC ]] && _CC= || _CC="CC=$CC"
    [[ -z $CFLAGS ]] && _CFLAGS= || _CFLAGS="CFLAGS=$CFLAGS"
    make "$_CC" "$_CFLAGS"
  requirements:
    build-dep:
      - git
- url: "https://github.com/ggreer/the_silver_searcher"
  build: |-
    ./autogen.sh
    mkdir build && cd build
    ../configure
    make
  requirements:
    build-dep:
      - silversearcher-ag
- url: "https://github.com/tmux/tmux"
  build: |-
    ./autogen.sh
    ./configure
    make
  requirements:
    build-dep:
      - tmux
    packages:
      - bison
- url: "https://github.com/curl/curl"
  build: |-
    ./buildconf
    mkdir build && cd build
    ../configure
    make
  requirements:
    build-dep:
      - curl
- url: "https://github.com/netdata/netdata/"
  build: |-
    autoreconf -fi
    ./configure
    make
  requirements:
    build-dep:
      - netdata
    packages:
      - libuv1-dev
- url: "https://github.com/php/php-src"
  branch: "PHP-7.2.28"
  build: |-
    ./buildconf
    ./configure
    make
  requirements:
    build-dep:
      - php7.2
- url: "https://github.com/antirez/redis"
  build: |-
    make
  requirements: []
- url: "https://github.com/jedisct1/libsodium"
  build: |-
    autoreconf -fi
    ./configure
    make check
