name: CI

on:
  push:
    branches: csmith

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39]
    steps:
      - uses: actions/checkout@v2
      - name: Install csmith
        run: |
            sudo apt-get update -qq
            sudo apt-get full-upgrade -y
            sudo apt-get install -y software-properties-common curl libtool build-essential automake

            curl https://apt.llvm.org/llvm-snapshot.gpg.key -o llvm.key
            sudo apt-key add llvm.key
            echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' | sudo tee -a /etc/apt/sources.list
            sudo apt-get update -qq
            sudo apt-get install -qq clang-10 llvm-10

            git clone --depth 1 https://github.com/csmith-project/csmith
            cd csmith
            autoreconf -fi
            ./configure --prefix=/usr
            sudo make install -j10
            sudo make install -C runtime install -j

      - name: Run experiment
        run: |
            mkdir ${{ matrix.batch }}
            cd ${{ matrix.batch }}

            for i in {0..1000} ; do
              echo $i
              csmith -o "$i.c"
              clang-10 -c -emit-llvm -O0 -Xclang -disable-O0-optnone "$i.c" -I ../csmith/runtime -o "$i.bc" &> /dev/null
              opt-10 -strip -O1 "$i.bc" -o "$i-strip-O1.bc"
              opt-10 -strip -O2 "$i.bc" -o "$i-strip-O2.bc"
              opt-10 -strip -O3 "$i.bc" -o "$i-strip-O3.bc"
            done

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.batch }}
          path: ${{ matrix.batch }}
