name: CI

# Run on push with specific tag
on:
  push:
    branches: [master]
  schedule:
    # Once a month
    - cron: '0 0 1 * *'

jobs:
  dockerbuild:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config_target: [i3, git, the_silver_searcher, tmux, curl, netdata, php-src, redis, libsodium, verificatum-vec,
  verificatum-gmpmee, libsignal-protocol-c]
    env:
      CC: clang
      CXX: clang++
      CFLAGS: "-save-temps -O1"
      CPPFLAGS: "-save-temps -O1"
      CXXFLAGS: "-save-temps -O1"
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo sed -i -e 's/# deb-src/deb-src/' /etc/apt/sources.list
          sudo apt-get update -qq
          sudo apt-get install -y software-properties-common build-essential automake cmake ninja-build meson curl
          curl https://apt.llvm.org/llvm-snapshot.gpg.key -o /tmp/llvm.key
          sudo apt-key add /tmp/llvm.key
          echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' | sudo tee -a /etc/apt/sources.list
           sudo apt-get update -qq
           sudo apt-get install -y clang-10 llvm-10
      - name: Install project
        run: |
          pip install -r requirements.txt
          ./build_reqs.py -v --whitelist=${{ matrix.config_target }} | sudo sh
      - run: PATH="/usr/lib/llvm-10/bin:$PATH" ./compile.py -ev --whitelist=${{ matrix.config_target }}
      - run: PATH="/usr/lib/llvm-10/bin:$PATH" ./postprocess.py --whitelist=${{ matrix.config_target}} -O2,3 -v strip opt dis
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: logs
